version: "3"
services:
  nest-api:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - postgres-nest:/data/postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgrespw'
      POSTGRES_DB: 'olp_backend'
      
volumes:
  postgres-nest: